/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vista;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import static vista.VistaRequerimientos.controlador;

/**
 *
 * @author sebas
 */
public class Lógin extends javax.swing.JFrame {

    /** Creates new form Lógin */
    public Lógin() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        actualizarTabla();
        actualizarTabla_2();
        actualizarTabla_3();
        jPConsultas_sub.setVisible(false);
        jPSub_panel2.setVisible(false);
        jPSubConsulta3.setVisible(false);
        
    }
    public void actualizarTabla() throws SQLException{
        ArrayList<modelo.Requerimiento_1> requerimiento1= controlador.consultarRequerimiento1();
        
        DefaultTableModel modelo = (DefaultTableModel) jTConsulta_1.getModel();
        
        while (modelo.getRowCount() > 0){
         modelo.removeRow(0);
        }
        
        int numcols = modelo.getColumnCount();
        for (modelo.Requerimiento_1 reque: requerimiento1){
            Object[] fila = new Object[numcols];
            
            fila[0] = reque.getConstructora();
            fila[1] = reque.getCiudad();
            fila[2] = reque.getBanco();
            fila[3] = reque.getPorcentaje();
            fila[4] = reque.getClasificacion();
            fila[5] = reque.getFecha();
                    
            modelo.addRow(fila);
        }
    }
    public void actualizarTabla_2() throws SQLException{
        ArrayList<modelo.Requerimiento_2> requerimiento2= controlador.consultarRequerimiento2();
        
        DefaultTableModel modelo = (DefaultTableModel) jTConsulta_2.getModel();
        
        while (modelo.getRowCount() > 0){
         modelo.removeRow(0);
        }
        
        int numcols = modelo.getColumnCount();
        for (modelo.Requerimiento_2 reque: requerimiento2){
            Object[] fila = new Object[numcols];
            
            fila[0] = reque.getConstructora();
            fila[1] = reque.getProveedor();
            fila[2] = reque.getPagado();
            
            modelo.addRow(fila);
        }
    }
    public void actualizarTabla_3() throws SQLException{
    
        ArrayList<modelo.Requerimiento_3> requerimiento3 = controlador.consultarRequerimiento3();
        
        DefaultTableModel modelo = (DefaultTableModel) jTConsulta_3.getModel();
        
        while (modelo.getRowCount() > 0){
            modelo.removeRow(0);
        }
        
        int numcols = modelo.getColumnCount();
        for(modelo.Requerimiento_3 requ: requerimiento3){
            Object[] fila = new Object [numcols];
        
            fila[0] = requ.getCargo();
            fila[1] = requ.getMaxSalario();
            
            modelo.addRow(fila);
        }
        
    }
    
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBConsulta = new javax.swing.JButton();
        jPConsultas_sub = new javax.swing.JPanel();
        jBConsul_1 = new javax.swing.JButton();
        jBConsul_2 = new javax.swing.JButton();
        jBConsul_3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTPanel_control = new javax.swing.JTabbedPane();
        jPrimera_entrada = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPSub_panel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPSubConsulta3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPconsul_1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTConsulta_1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTConsulta_2 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTConsulta_3 = new javax.swing.JTable();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(93, 94, 91));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(93, 94, 91));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(115, 147, 147));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 20));

        jPanel2.setBackground(new java.awt.Color(115, 147, 147));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(190, 167, 152));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/exit.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 50, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/user.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 60, 60));

        jBConsulta.setBackground(new java.awt.Color(190, 167, 152));
        jBConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/book.png"))); // NOI18N
        jBConsulta.setBorder(null);
        jBConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBConsultaMouseEntered(evt);
            }
        });
        jBConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultaActionPerformed(evt);
            }
        });
        jPanel2.add(jBConsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 110, 40));

        jPConsultas_sub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPConsultas_subMouseEntered(evt);
            }
        });
        jPConsultas_sub.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBConsul_1.setBackground(new java.awt.Color(93, 94, 91));
        jBConsul_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/level_1.png"))); // NOI18N
        jBConsul_1.setBorder(null);
        jBConsul_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBConsul_1MousePressed(evt);
            }
        });
        jBConsul_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsul_1ActionPerformed(evt);
            }
        });
        jPConsultas_sub.add(jBConsul_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 21, 110, 33));

        jBConsul_2.setBackground(new java.awt.Color(93, 94, 91));
        jBConsul_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/level_2.png"))); // NOI18N
        jBConsul_2.setBorder(null);
        jBConsul_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBConsul_2MouseClicked(evt);
            }
        });
        jPConsultas_sub.add(jBConsul_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 65, 110, 33));

        jBConsul_3.setBackground(new java.awt.Color(93, 94, 91));
        jBConsul_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/level_3.png"))); // NOI18N
        jBConsul_3.setBorder(null);
        jBConsul_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBConsul_3MouseClicked(evt);
            }
        });
        jPConsultas_sub.add(jBConsul_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 109, 110, 33));

        jPanel2.add(jPConsultas_sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 110, 160));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Conectado");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 480));

        jTPanel_control.setBackground(new java.awt.Color(93, 94, 91));

        jPrimera_entrada.setBackground(new java.awt.Color(93, 94, 91));
        jPrimera_entrada.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(190, 167, 152));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("CONSTRUCTORA COLOMBIA S.A.");
        jPrimera_entrada.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 590, 100));

        jPanel6.setBackground(new java.awt.Color(115, 147, 147));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, new java.awt.Color(240, 240, 240), new java.awt.Color(240, 240, 240)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/combo_chart.png"))); // NOI18N
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 110));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Administ");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/downloading_updates.png"))); // NOI18N
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Estado");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/administrator_male.png"))); // NOI18N
        jPanel6.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Descarga");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jPrimera_entrada.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 180, 280));

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(190, 167, 152));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ajustes");
        jButton1.setBorder(null);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 110, 30));

        jButton2.setBackground(new java.awt.Color(190, 167, 152));
        jButton2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Perfil");
        jButton2.setBorder(null);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 110, 30));

        jPrimera_entrada.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 480, 50));

        jPSub_panel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPSub_panel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPSub_panel2MouseExited(evt);
            }
        });
        jPSub_panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_level_up_48px_1.png"))); // NOI18N
        jLabel10.setText("Actualizar");
        jPSub_panel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_new_message_48px.png"))); // NOI18N
        jLabel12.setText("Mensajeria");
        jPSub_panel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_location_48px.png"))); // NOI18N
        jLabel13.setText("Sede");
        jPSub_panel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jPrimera_entrada.add(jPSub_panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 160, 240));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_schedule_48px.png"))); // NOI18N
        jPrimera_entrada.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 60, 50));

        jPSubConsulta3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPSubConsulta3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPSubConsulta3MouseExited(evt);
            }
        });
        jPSubConsulta3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_add_user_male_48px.png"))); // NOI18N
        jLabel14.setText("Actualizar");
        jPSubConsulta3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/Bandercolombia_48px.png"))); // NOI18N
        jLabel15.setText("Idioma");
        jPSubConsulta3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, -1));

        jPrimera_entrada.add(jPSubConsulta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 150, 240));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_postal_48px.png"))); // NOI18N
        jPrimera_entrada.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/imagenes/icons8_wi-fi_good_48px_1.png"))); // NOI18N
        jPrimera_entrada.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, -1, -1));

        jTPanel_control.addTab("tab4", jPrimera_entrada);

        jPconsul_1.setBackground(new java.awt.Color(93, 94, 91));

        jTConsulta_1.setBackground(new java.awt.Color(93, 94, 91));
        jTConsulta_1.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTConsulta_1.setForeground(new java.awt.Color(255, 255, 255));
        jTConsulta_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Constructora", "Ciudad", "Banco", "Porcentaje", "Clasificacion", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(jTConsulta_1);

        javax.swing.GroupLayout jPconsul_1Layout = new javax.swing.GroupLayout(jPconsul_1);
        jPconsul_1.setLayout(jPconsul_1Layout);
        jPconsul_1Layout.setHorizontalGroup(
            jPconsul_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        jPconsul_1Layout.setVerticalGroup(
            jPconsul_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPconsul_1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTPanel_control.addTab("tab4", jPconsul_1);

        jPanel3.setBackground(new java.awt.Color(93, 94, 91));

        jTConsulta_2.setBackground(new java.awt.Color(93, 94, 91));
        jTConsulta_2.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTConsulta_2.setForeground(new java.awt.Color(255, 255, 255));
        jTConsulta_2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Constructora", "Proveedor", "Pagado"
            }
        ));
        jScrollPane2.setViewportView(jTConsulta_2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        jTPanel_control.addTab("tab2", jPanel3);

        jPanel4.setBackground(new java.awt.Color(93, 94, 91));

        jTConsulta_3.setBackground(new java.awt.Color(93, 94, 91));
        jTConsulta_3.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
        jTConsulta_3.setForeground(new java.awt.Color(255, 255, 255));
        jTConsulta_3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Cargo", "MaxSalario"
            }
        ));
        jScrollPane3.setViewportView(jTConsulta_3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 381, Short.MAX_VALUE))
        );

        jTPanel_control.addTab("tab3", jPanel4);

        jPanel1.add(jTPanel_control, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, -10, 860, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBConsul_1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBConsul_1MousePressed
        
        jTPanel_control.setSelectedIndex(1);
        
    }//GEN-LAST:event_jBConsul_1MousePressed

    private void jBConsul_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsul_1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jBConsul_1ActionPerformed

    private void jBConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultaActionPerformed
        // TODO add your handling code here:
        jPConsultas_sub.setVisible(false);
        jTPanel_control.setSelectedIndex(0);
    }//GEN-LAST:event_jBConsultaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jBConsul_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBConsul_2MouseClicked
        // TODO add your handling code here:
        jTPanel_control.setSelectedIndex(2);
    }//GEN-LAST:event_jBConsul_2MouseClicked

    private void jBConsul_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBConsul_3MouseClicked
        // TODO add your handling code here:
        jTPanel_control.setSelectedIndex(3);
    }//GEN-LAST:event_jBConsul_3MouseClicked

    private void jPConsultas_subMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPConsultas_subMouseEntered
        // TODO add your handling code here:
        jPConsultas_sub.setVisible(true);
    }//GEN-LAST:event_jPConsultas_subMouseEntered

    private void jBConsultaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBConsultaMouseEntered
        // TODO add your handling code here:
        jPConsultas_sub.setVisible(true);
    }//GEN-LAST:event_jBConsultaMouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1MouseExited

    private void jPSub_panel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPSub_panel2MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPSub_panel2MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPSub_panel2.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton2MouseExited

    private void jPSubConsulta3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPSubConsulta3MouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jPSubConsulta3MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jPSubConsulta3.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPSub_panel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPSub_panel2MouseEntered
        // TODO add your handling code here:
        jPSub_panel2.setVisible(true);
    }//GEN-LAST:event_jPSub_panel2MouseEntered

    private void jPSubConsulta3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPSubConsulta3MouseEntered
        // TODO add your handling code here:
        jPSubConsulta3.setVisible(true);
    }//GEN-LAST:event_jPSubConsulta3MouseEntered

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        jPSub_panel2.setVisible(true);
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
        jPSubConsulta3.setVisible(true);
    }//GEN-LAST:event_jButton2MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lógin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lógin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lógin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lógin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Lógin().setVisible(false);
                    
                } catch (Exception e) {
                    System.out.println("sistema mal");
                } 
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBConsul_1;
    private javax.swing.JButton jBConsul_2;
    private javax.swing.JButton jBConsul_3;
    private javax.swing.JButton jBConsulta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPConsultas_sub;
    private javax.swing.JPanel jPSubConsulta3;
    private javax.swing.JPanel jPSub_panel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPconsul_1;
    private javax.swing.JPanel jPrimera_entrada;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTConsulta_1;
    private javax.swing.JTable jTConsulta_2;
    private javax.swing.JTable jTConsulta_3;
    private javax.swing.JTabbedPane jTPanel_control;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
