/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorRequerimientos;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sebas
 */
public class Pimera_parte extends javax.swing.JFrame {

    /**
     * Creates new form Pimera_parte
     */
    public Pimera_parte() throws SQLException {
        initComponents();
        this.setLocationRelativeTo(null);
        Sistema();
            
        
        
    }

    public void Sistema() throws SQLException{
            String usuario = jTUsuario.getText();
            String clave = String.valueOf(jPassword.getPassword());
            Registro reg = new Registro();
            String usuari=reg.getUsuario();
            String contrasi = reg.getContras();
            
            
            
            
            if((usuario.equals(usuari)) && (clave.equals(contrasi))){
            JOptionPane.showMessageDialog(null, "Bienvenido al Sistema");
            
            Lógin log = new Lógin();
            log.setVisible(true);
            
            
            
            this.dispose();
            
            
            } else {
                
                jTUsuario.setText(null);
                jPassword.setText("");
                
            }
                      
            }
           
       
    
    public void Registrarse() throws SQLException{
        
        Registro reg = new Registro();
        reg.setVisible(true);
        this.dispose();
        
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPLogin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTUsuario = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jBEntrar = new javax.swing.JButton();
        jPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBSalida = new javax.swing.JButton();
        jBRegistro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(93, 94, 91));
        jPanel2.setForeground(new java.awt.Color(117, 200, 177));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPLogin.setBackground(new java.awt.Color(115, 147, 147));
        jPLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(29, 33, 33), 2));
        jPLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(93, 94, 91));
        jLabel4.setText("Usuario");
        jPLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 86, 35));

        jTUsuario.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTUsuario.setBorder(null);
        jTUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTUsuarioActionPerformed(evt);
            }
        });
        jPLogin.add(jTUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 330, 49));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(93, 94, 91));
        jLabel5.setText("Contraseña");
        jPLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jBEntrar.setBackground(new java.awt.Color(190, 167, 152));
        jBEntrar.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jBEntrar.setText("Login");
        jBEntrar.setBorder(null);
        jBEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEntrarActionPerformed(evt);
            }
        });
        jPLogin.add(jBEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 330, 49));

        jPassword.setText("jPasswordField1");
        jPLogin.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 330, 49));

        jPanel2.add(jPLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 390, 430));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(190, 167, 152));
        jLabel1.setText("Bienvenido");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 290, 120));

        jSeparator1.setForeground(new java.awt.Color(190, 167, 152));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 400, 420, 20));

        jSeparator2.setForeground(new java.awt.Color(190, 167, 152));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 420, 60));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(190, 167, 152));
        jLabel2.setText("¿Perdiste tu contraseña?");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 180, 70));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(190, 167, 152));
        jLabel3.setText("¿No tienes Cuenta? Registrate");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, -1));

        jBSalida.setBackground(new java.awt.Color(190, 167, 152));
        jBSalida.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jBSalida.setText("Salir");
        jBSalida.setBorder(null);
        jBSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalidaActionPerformed(evt);
            }
        });
        jPanel2.add(jBSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 40, 20));

        jBRegistro.setBackground(new java.awt.Color(190, 167, 152));
        jBRegistro.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jBRegistro.setText("Registro");
        jBRegistro.setBorder(null);
        jBRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRegistroActionPerformed(evt);
            }
        });
        jPanel2.add(jBRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 360, 80, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTUsuarioActionPerformed
        this.dispose();
    }//GEN-LAST:event_jTUsuarioActionPerformed

    private void jBEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEntrarActionPerformed
        try {
            Sistema();
        } catch (SQLException ex) {
            Logger.getLogger(Pimera_parte.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBEntrarActionPerformed

    private void jBRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRegistroActionPerformed
        try {
            Registrarse();
        } catch (SQLException ex) {
            Logger.getLogger(Pimera_parte.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBRegistroActionPerformed

    private void jBSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalidaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBSalidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pimera_parte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pimera_parte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pimera_parte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pimera_parte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Pimera_parte().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Pimera_parte.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEntrar;
    private javax.swing.JButton jBRegistro;
    private javax.swing.JButton jBSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPLogin;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTUsuario;
    // End of variables declaration//GEN-END:variables
}
